version: '3'

volumes:
  data_dev: {}

services:
  rsa_encryption:
    build:
      context: .
      dockerfile: ./compose/rsa_encryption/Dockerfile-dev
    environment:
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
      - ENVTYPE=dev
    #env-file:
    #  - ./.envs/.dev/.rsa_encryption
    image: rsa_encryption:dev
    volumes:
      - .:/app
      - data_dev:/data
    #command: /start
